name: chat_bubbles
description: Flutter chat bubble widgets, similar to Whatsapp and more shapes. Easy to use and implement
  chat bubbles.
version: 1.4.1
homepage: https://github.com/prahack/chat_bubbles

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  flutter_decorated_text: ^1.0.12
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

